CREATE TABLE [Dimension].[Date] (
    [Date_Key]                      INT          NOT NULL,
    [Calendar_Date]                 DATE         NOT NULL,
    [Calendar_Date_Time]            DATETIME     NOT NULL,
    [Calendar_Date_Name]            VARCHAR (25) NOT NULL,
    [Calendar_Extended_Date_Name]   VARCHAR (50) NOT NULL,
    [Calendar_Year_Number]          SMALLINT     NOT NULL,
    [Calendar_Year_Name]            VARCHAR (25) NOT NULL,
    [Calendar_Quarter_Number]       TINYINT      NOT NULL,
    [Calendar_Quarter_Name]         VARCHAR (25) NOT NULL,
    [Calendar_Month_Number]         TINYINT      NOT NULL,
    [Calendar_Month_Name]           VARCHAR (25) NOT NULL,
    [Calendar_Week_Day_Number]      TINYINT      NOT NULL,
    [Calendar_Week_Day_Name]        VARCHAR (25) NOT NULL,
    [Calendar_Week_Number]          TINYINT      NOT NULL,
    [Calendar_Week_Name]            VARCHAR (25) NOT NULL,
    [Calendar_Week_Range_Name]      VARCHAR (50) NOT NULL,
    [Calendar_Week_of_Month_Number] TINYINT      NOT NULL,
    [Calendar_Week_of_Month_Name]   VARCHAR (25) NOT NULL,
    [Timesheet_Week_Start_Date]     DATE         NOT NULL,
    [Timesheet_Week_End_Date]       DATE         NOT NULL,
    [Timesheet_Week_Range_Name]     VARCHAR (50) NOT NULL,
    [Timesheet_Week_Ending_Name]    VARCHAR (50) NOT NULL,
    [Timesheet_Week_of_Month]       TINYINT      NOT NULL,
    [Is_Week_Day]                   BIT          NOT NULL,
    [Is_Weekend]                    BIT          NOT NULL,
    [Is_Holiday]                    BIT          NOT NULL,
    [Is_Utilization_Data_Loaded]    BIT          NOT NULL,
    [Insert_Date]                   DATETIME     NOT NULL,
    [Update_Date]                   DATETIME     NULL
);

