CREATE TABLE [Dimension].[Employee_History] (
    [Employee_History_Key]         INT            NOT NULL,
    [Employee_History_Key_Manager] INT            NOT NULL,
    [Employee_Code]                VARCHAR (10)   NOT NULL,
    [Organizational_Unit]          VARCHAR (10)   NOT NULL,
    [Practice_Group]               VARCHAR (50)   NOT NULL,
    [Region]                       VARCHAR (50)   NOT NULL,
    [Market]                       VARCHAR (50)   NOT NULL,
    [City]                         VARCHAR (50)   NOT NULL,
    [Cost_Center_Code]             VARCHAR (20)   NOT NULL,
    [Cost_Center_Name]             VARCHAR (50)   NOT NULL,
    [Employee_Type_Code]           VARCHAR (10)   NOT NULL,
    [Employee_Type_Name]           VARCHAR (50)   NOT NULL,
    [First_Name]                   VARCHAR (50)   NOT NULL,
    [Last_Name]                    VARCHAR (50)   NOT NULL,
    [Employee_Name]                VARCHAR (101)  NOT NULL,
    [Position_Code]                VARCHAR (10)   NOT NULL,
    [Position_Name]                VARCHAR (50)   NOT NULL,
    [Standard_Loaded_Rate]         MONEY          NOT NULL,
    [Utilization_Target]           DECIMAL (5, 2) NOT NULL,
    [Email_Address]                VARCHAR (200)  NOT NULL,
    [Domain_Login]                 VARCHAR (50)   NOT NULL,
    [Hire_Date]                    DATE           NOT NULL,
    [Exclude_From_Utilization]     BIT            NOT NULL,
    [Effective_Date]               DATE           NOT NULL,
    [Termination_Date]             DATE           NOT NULL,
    [Current_Record]               BIT            NOT NULL,
    [Insert_Date]                  DATETIME       NOT NULL,
    [Update_Date]                  DATETIME       NULL,
    [Practice]                     VARCHAR (30)   NULL
);

