CREATE TABLE [Dimension].[Project] (
    [Project_Key]                         INT             NOT NULL,
    [Contract_Number]                     VARCHAR (20)    NOT NULL,
    [Contract_Name]                       VARCHAR (100)   NOT NULL,
    [WBS_Element]                         VARCHAR (30)    NOT NULL,
    [WBS_Element_Description]             VARCHAR (100)   NOT NULL,
    [Project_Number]                      VARCHAR (30)    NOT NULL,
    [Project_Type_Code]                   VARCHAR (10)    NOT NULL,
    [Project_Type_Name]                   VARCHAR (100)   NOT NULL,
    [Employee_Code_Profit_Center_Manager] VARCHAR (10)    NOT NULL,
    [Employee_Code_Project_Manager]       VARCHAR (10)    NOT NULL,
    [Employee_Code_Financial_Admin]       VARCHAR (10)    NOT NULL,
    [Employee_Code_Forecast_Approval]     VARCHAR (10)    NOT NULL,
    [Customer_Code]                       VARCHAR (25)    NOT NULL,
    [Customer_Group]                      VARCHAR (50)    NOT NULL,
    [Cost_Center_Code]                    VARCHAR (20)    NOT NULL,
    [Cost_Center_Name]                    VARCHAR (50)    NOT NULL,
    [Cost_Center_City]                    VARCHAR (50)    NOT NULL,
    [Cost_Center_Practice_Group]          VARCHAR (50)    NOT NULL,
    [Cost_Center_Organizational_Unit]     VARCHAR (10)    NOT NULL,
    [Cost_Center_Market]                  VARCHAR (50)    NOT NULL,
    [Cost_Center_Region]                  VARCHAR (50)    NOT NULL,
    [Profit_Center_Code]                  VARCHAR (20)    NOT NULL,
    [Profit_Center_Name]                  VARCHAR (50)    NOT NULL,
    [Profit_Center_Organizational_Unit]   VARCHAR (50)    NOT NULL,
    [Profit_Center_Segment]               VARCHAR (50)    NOT NULL,
    [Profit_Center_Region]                VARCHAR (50)    NOT NULL,
    [Profit_Center_Market]                VARCHAR (50)    NOT NULL,
    [Profit_Center_Budget]                VARCHAR (100)   NOT NULL,
    [Profit_Center_Sales_Group_Code]      VARCHAR (10)    NOT NULL,
    [Profit_Center_Sales_Group_Name]      VARCHAR (100)   NOT NULL,
    [Project_Start_Date]                  DATE            NOT NULL,
    [Project_End_Date]                    DATE            NOT NULL,
    [Gross_Value]                         MONEY           NOT NULL,
    [Insert_Date]                         DATETIME        NOT NULL,
    [Update_Date]                         DATETIME        NULL,
    [Employee_Code_CSM]                   VARCHAR (10)    NOT NULL,
    [Employee_Code_Staffing]              VARCHAR (10)    NOT NULL,
    [Booked_Cost_Baseline]                MONEY           NOT NULL,
    [Booked_Cost]                         MONEY           NOT NULL,
    [Booked_Margin_Baseline]              DECIMAL (12, 4) NOT NULL,
    [Booked_Margin]                       DECIMAL (12, 4) NOT NULL,
    [WBS_Status_Code]                     NUMERIC (3)     NULL,
    [WBS_Status_Code_Desc]                VARCHAR (40)    NULL
);

