CREATE TABLE [Fact].[Project_Transaction] (
    [Project_Transaction_Key]       INT             NOT NULL,
    [Date_Key]                      INT             NOT NULL,
    [Cost_Element_Key]              INT             NOT NULL,
    [Project_Key]                   INT             NOT NULL,
    [Project_Resource_Key]          INT             NOT NULL,
    [Customer_Key]                  INT             NOT NULL,
    [Vendor_Key]                    INT             NOT NULL,
    [Employee_Key_Resource]         INT             NOT NULL,
    [Employee_History_Key_Resource] INT             NOT NULL,
    [Employee_Key_Project_Manager]  INT             NOT NULL,
    [Document_Type]                 VARCHAR (10)    NOT NULL,
    [Document_Number]               VARCHAR (20)    NOT NULL,
    [Posting_Row]                   VARCHAR (10)    NOT NULL,
    [Entry_Sheet]                   VARCHAR (20)    NOT NULL,
    [Line_Number]                   VARCHAR (30)    NOT NULL,
    [Cost_Element_Code]             VARCHAR (20)    NOT NULL,
    [Reference_Transaction]         VARCHAR (10)    NOT NULL,
    [Bill_Rate]                     MONEY           NOT NULL,
    [Overtime_Rate]                 MONEY           NOT NULL,
    [Non_Billable_Rate]             MONEY           NOT NULL,
    [Billable_Hours]                DECIMAL (10, 2) NOT NULL,
    [Overtime_Hours]                DECIMAL (10, 2) NOT NULL,
    [Non_Billable_Hours]            DECIMAL (10, 2) NOT NULL,
    [Revenue_Amount]                MONEY           NOT NULL,
    [Expense_Amount]                MONEY           NOT NULL,
    [Reimbursable_Expense]          BIT             NOT NULL,
    [Transaction_Description]       VARCHAR (50)    NOT NULL,
    [Insert_Date]                   DATETIME        NOT NULL,
    [Update_Date]                   DATETIME        NULL
);

